---

- name: Prepare
  hosts: all
  become: True
  vars:
    murmur_sslcert: "/etc/ssl/mumble-server-cert.pem"
    murmur_sslkey: "/etc/ssl/mumble-server-key.pem"
    nodejs_install_npm_user: root
  tasks:
    - name: Install OpenSSL
      apt:
        pkg: openssl
        cache_valid_time: 3600

    - name: create self-signed SSL cert
      command: openssl req -new -nodes -x509 -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN=${ansible_fqdn}" -days 3650 -keyout {{ murmur_sslkey }} -out {{ murmur_sslcert }} -extensions v3_ca
      args:
        creates: "{{ murmur_sslcert }}"
