gamemaster_user: gamemaster
gamemaster_password: foobarbuz
electrixx_begin: "202312011200Z"
electrixx_end: "202312031600Z"
electrixx_version: invite

GATEWAY_INTERFACE: enp3s4f1
# with dialin ppp0 is EXTERNAL_INTERFACE
EXTERNAL_INTERFACE: enp3s4f0
INTERNAL_INTERFACE: enp3s4f1


GATEWAY_IP: 10.57.82.1
INTERNAL_IP: 10.57.82.2
EXTERNAL_IP: "{{ ansible_facts[EXTERNAL_INTERFACE].ipv4.address }}"

# mumble
murmur_welcometext: "Welcome on Electrixx {{ electrixx_version }} mumble server!"
murmur_uname: "{{ lookup('pipe', 'uname -n') }}"
murmur_port: "64738"
murmur_host: "0.0.0.0"
murmur_serverpassword: "{{ gamemaster_password }}"
# name for root channel and entry in mumble main server list
murmur_registername: "{{ gamemaster_user }}"
  
murmur_registerpassword: "{{ gamemaster_password | password_hash('sha512') }}"
# regexp to validate channel or usernames
murmur_channelname: "Electrixx$"
  
murmur_username: "Electrixx$"

murmur_sslcert: "/etc/ssl/mumble-server-cert.pem"
murmur_sslkey: "/etc/ssl/mumble-server-key.pem"
murmur_sslca: "/etc/ssl/mumble-server-cert.pem"

# vsftpd
vsftpd_cert_file: "/etc/ssl/vsftpd-server-cert.pem"
vsftpd_key_file: "/etc/ssl/vsftpd-server-key.pem"
# config variables
vsftpd_config:
        listen: true
        anonymous_enable: true
        write_enable: true
        pasv_enable: true
        pasv_min_port: 10000
        pasv_max_port: 10100
        ftpd_banner: "Welcome on Electrixx {{ electrixx_version }} FTP Server."
        allow_writeable_chroot: true
        xferlog_file: "/var/log/vsftpd.log"
        anon_upload_enable: true
        anon_root: "/home/ftpuser/upload"
        anon_mkdir_write_enable: true
        anon_other_write_enable: true
        dirmessage_enable: true

vsftpd_users:
       - username: ftpuser
         password: ''


# DHCPD
# Configuration settings for the daemon.
dhcpd_ipv4_interface: "{{ INTERNAL_INTERFACE }}"

# Setting applicable for the global scope.
dhcpd_default_lease_time: 600
dhcpd_max_lease_time: 7200
dhcpd_subnet_mask: 255.255.255.0
dhcpd_broadcast_address: 10.57.82.255
dhcpd_routers: "{{ GATEWAY_IP }}"
dhcpd_domain_name_servers: 9.9.9.9, 8.8.8.8
dhcpd_domain_search: "{{electrixx_version}}.electrixx.lan,electrixx.lan"

# The image to serve for PXE booting.
#dhcpd_filename: pxelinux.0
dhcpd_filename: ""
# Where the image can be downloaded from.
dhcpd_next_server: "{{ GATEWAY_IP }}"

# DHCP works with subnets, a list containing properties per subnet.
subnetmask: 24
dhcpd_subnets:
  - network: 10.57.82.0
    netmask: 255.255.255.0
    range_start: 10.57.82.10
    range_end: 10.57.82.200

# DHCP works with extra Hosts
dhcpd_hosts:
  - server_name: "bf3.{{ electrixx_version }}.electrixx.lan"
    hardware_ethernet: "04:7c:16:B8:0c:88"
    fixed_address: "10.57.82.3"

# UFW
# https://gist.github.com/kimus/9315140
# Configuration object passed to the configuration file
ufw_config:
  IPV6: "yes"
  DEFAULT_INPUT_POLICY: DROP
  DEFAULT_OUTPUT_POLICY: ACCEPT
  DEFAULT_FORWARD_POLICY: ACCEPT
  DEFAULT_APPLICATION_POLICY: SKIP
  MANAGE_BUILTINS: "no"
  IPT_SYSCTL: /etc/ufw/sysctl.conf
  IPT_MODULES: ""
ufw_rules:
  # Set loggin
  - logging: "low"
  # Allow OpenSSH
  - rule: allow
    name: OpenSSH
    to_ip: "{{ INTERNAL_IP }}"
  - rule: allow
    name: OpenSSH
    to_ip: "{{ EXTERNAL_IP }}"
  # Allow vsftpd
  - rule: allow
    to_port: 21
    proto: tcp
  # Allow vsftpd pasv
  - rule: allow
    to_port: "{{ vsftpd_config.pasv_min_port }}:{{ vsftpd_config.pasv_max_port }}"
    proto: tcp
    to_ip: "{{ INTERNAL_IP }}"
  # Allow mumble
  - rule: allow
    to_port: "{{ murmur_port }}"
    proto: tcp
    to_ip: "{{ INTERNAL_IP }}"
  # Allow all access to tcp port 80,443
  - rule: allow
    name: WWW Full
    to_ip: "{{ INTERNAL_IP }}"
  # Steam CS GO
  - rule: allow
    proto: tcp
    to_port: 27015:27030,27036,2703
    to_ip: "{{ INTERNAL_IP }}"
  - rule: allow
    proto: udp
    to_port: 4380,27000:27031,27036
    to_ip: "{{ INTERNAL_IP }}"
