gamemaster_user: gamemaster
gamemaster_password: foobarbuz
electrixx_begin: "202111191300Z"
electrixx_end: "202111212000Z"
electrixx_version: Lambda

# mumble
murmur_welcometext: "Welcome on Electrixx {{ electrixx_version }} mumble server!"
murmur_uname: "{{ lookup('pipe', 'uname -n') }}"
murmur_port: "64738"
murmur_host: "0.0.0.0"
murmur_serverpassword: "{{ gamemaster_password }}"
# name for root channel and entry in mumble main server list
murmur_registername: "{{ gamemaster_user }}"
  
murmur_registerpassword: "{{ gamemaster_password | password_hash('sha512') }}"
# regexp to validate channel or usernames
murmur_channelname: "Electrixx$"
  
murmur_username: "Electrixx$"

murmur_sslcert: "/etc/ssl/mumble-server-cert.pem"
murmur_sslkey: "/etc/ssl/mumble-server-key.pem"
murmur_sslca: "/etc/ssl/mumble-server-cert.pem"

# vsftpd
vsftpd_cert_file: "/etc/ssl/vsftpd-server-cert.pem"
vsftpd_key_file: "/etc/ssl/vsftpd-server-key.pem"
# config variables
vsftpd_config:
        listen: true
        anonymous_enable: true
        write_enable: true
        pasv_enable: true
        pasv_min_port: 10000
        pasv_max_port: 10100
        ftpd_banner: "Welcome on Electrixx {{ electrixx_version }} FTP Server."

vsftpd_users:
       - username: ftpuser
         password: ''


# DHCPD
# Configuration settings for the daemon.
dhcpd_ipv4_interface: "{{ ansible_default_ipv4.interface | default('enp2s0') }}"

# Setting applicable for the global scope.
dhcpd_default_lease_time: 600
dhcpd_max_lease_time: 7200
dhcpd_subnet_mask: 255.255.255.0
dhcpd_broadcast_address: 10.0.2.255
dhcpd_routers: 10.0.2.254
dhcpd_domain_name_servers: 141.56.1.1, 141.56.1.2
dhcpd_domain_search: "{{electrixx_version}}.electrixx.lan"

# The image to serve for PXE booting.
#dhcpd_filename: pxelinux.0
# Where the image can be downloaded from.
dhcpd_next_server: 10.0.2.254

# DHCP works with subnets, a list containing properties per subnet.
dhcpd_subnets:
  - network: 10.0.2.0
    netmask: 255.255.255.0
    range_start: 10.0.2.1
    range_end: 10.0.2.100



# UFW
# https://gist.github.com/kimus/9315140
# Configuration object passed to the configuration file
ufw_config:
  IPV6: "yes"
  DEFAULT_INPUT_POLICY: DROP
  DEFAULT_OUTPUT_POLICY: ACCEPT
  DEFAULT_FORWARD_POLICY: ACCEPT
  DEFAULT_APPLICATION_POLICY: SKIP
  MANAGE_BUILTINS: "no"
  IPT_SYSCTL: /etc/ufw/sysctl.conf
  IPT_MODULES: ""
ufw_rules:
  # Set loggin
  - logging: "full"
  # Allow OpenSSH
  - rule: allow
    name: OpenSSH
    proto: tcp
  # Allow vsftpd
  - rule: allow
    to_port: 21
    proto: tcp
  # Allow vsftpd pasv
  - rule: allow
    to_port: "{{ vsftpd_config.pasv_min_port }}:{{ vsftpd_config.pasv_max_port }}"
    proto: tcp
  # Allow mumble
  - rule: allow
    to_port: "{{ murmur_port }}"
    proto: tcp
  # Allow all access to tcp port 80,443
  - rule: allow
    name: WWW Full
