---
- name: Install Left 4 Dead 2
  shell: "{{ steamcmd_exe }} {{ l4d2_steamcmd_args }}"

- name: install server.cfg
  template:
          backup: true
          src: server.cfg.j2
          dest: "{{ l4d2_server_cfg }}"

          #- name: download extra packages
          #  get_url:
          #          url: "{{ item }}"
          #          dest: "{{ L4D2_HOME }}/"
          #  with_items: "{{ l4d2_extras }}"
          #  ignore_errors: true

          #- name: unarchive extra packages
          #  unarchive:
          #          remote_src: true
          #          src: "{{ CSGO_HOME }}/{{ item | basename }}"
          #          dest: "{{ CSGO_HOME }}"
          #  with_items: "{{csgo_extras}}"
          #  ignore_errors: true

- say:
        msg: '
        Server starten

        cd $HOME/steam/server/l4d2
        tmux
        ./srcds_run -usercon -console -game left4dead2 +port 27020 +maxplayers 8 +exec server.cfg +map c2m1_highway
        '
