---
- name: copy helper scripts
  template:
    src: "{{ item }}.j2"
    dest: "{{ lookup('env', 'HOME') }}/{{item}}"
  loop:
    - GAMESERVER.sh
    - GAMEUPGRADE.sh
  become_user: "{{ gamemaster_user }}"
  tags:
    - cs2
    - helper
