---

- include: mumble.yml

- include: mumble-web.yml
  when: mumble_web
  tags: mumble-web

- include: monitoring.yml
  when: murmur_monitoring_monit_enabled or murmur_monitoring_munin_enabled

- include: goss.yml
  tags:
    - goss
