---
- name: CJDNS | config exists?
  stat:
        path: $HOME/cjdroute.conf
  register: conf
  become: false

- name: CJDNS | generate config
  shell: umask 077 && ./cjdroute --genconf > /$HOME/cjdroute.conf
  args:
          chdir: /tmp/cjdns
  become: false
  when: conf.stat.exists == False

- name: CJDNS | load config
  shell: ./cjdroute --cleanconf < /$HOME/cjdroute.conf
  args:
          chdir: /tmp/cjdns
  become: false
  register: cjdnsconf_json

- set_fact:
        cjdnsconf: "{{ cjdnsconf_json.stdout | from_json | combine(cjdns_config) }}"

- debug:
        var: cjdnsconf

- name: CJDNS | admin config files
  template:
    src: cjdnsadmin.j2
    dest: $HOME/.cjdnsadmin
  become: false
