---
- name: CJDNS | install requirements
  apt:
          name: "{{ item }}"
  loop: "{{ cjdns_requirements }}"

- name: CJDNS | get git repo https://github.com/cjdelisle/cjdns
  git:
        repo: https://github.com/cjdelisle/cjdns
        dest: /tmp/cjdns
        #single_branch: yes
        version: "{{ cjdns_version }}"

- name: CJDNS | build
  shell: ./do
  args:
          chdir: /tmp/cjdns

- include: config.yml
  ignore_errors: true
  become: false

- include: service.yml
