---
- name: CJDNS | install requirements
  apt:
          name: "{{ item }}"
  loop: "{{ cjdns_requirements }}"

- name: CJDNS | get git repo https://github.com/cjdelisle/cjdns
  git:
        repo: https://github.com/cjdelisle/cjdns
        dest: /tmp/cjdns
        #single_branch: yes
        version: "{{ cjdns_version }}"

- name: CJDNS | build
  shell: ./do
  args:
          chdir: /tmp/cjdns

- name: CJDNS | create global exe
  copy:
          remote_src: true
          src: /tmp/cjdns/cjdroute
          dest: /usr/bin/cjdroute
          mode: 0750


- include: config.yml
  ignore_errors: true
  become: false

- include: dynamicEndpoint.yml
  when: cjdns_dynamicEndpoints is defined
  tags:
          - dynamicEndpoints

- include: service.yml
