---
- name: CJDNS | setup Service files
  copy:
          src: "/tmp/cjdns/contrib/systemd/{{ item }}"
          dest: "/etc/systemd/system/{{ item }}"
          remote_src: true
  loop:
          - cjdns.service
          - cjdns-resume.service

- name: CJDNS | enable systemd service
  service:
          enabled: true
          name: "{{ item }}"
          state: stopped
  loop:
          - cjdns
          - cjdns-resume
