---

- name: Includeing OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- import_tasks: install.yml
  tags:
    - networking
    - vsftpd
    - install
    - vsftpd-install

- import_tasks: config.yml
  tags:
    - networking
    - vsftpd
    - config
    - vsftpd-config

- import_tasks: manage.yml
  tags:
    - networking
    - vsftpd
    - manage
    - vsftpd-manage

- import_tasks: service.yml
  tags:
    - networking
    - vsftpd
    - service
    - vsftpd-service
