---
- hosts: all localhost
  become: true
  vars_files:
        - host_vars/electrixx-server.yml
  pre_tasks:
        - name: upgrade ansible
          apt_repository:
                repo: deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main
                state: present
                filename: ansible
          tags:
                - ansible

        - name: import ansible repo key
          apt_key:
                id: 93C4A3FD7BB9C367
                keyserver: keyserver.ubuntu.com
          tags:
                - ansible

        - name: add architecture i386
          shell: dpkg --add-architecture i386

        - name: install required packages
          apt:
                  name: "{{ item }}"
                  state: latest
                  update_cache: true
          loop:
                  - libx11-6:i386
                  - libxext6:i386
                  - libgl1-mesa-dri:i386
                  - libgl1-mesa-glx:i386
                  - tmux
                  - mailutils
                  - postfix
                  - ca-certificates
                  - lib32gcc1
                  - libstdc++6
                  - libstdc++6:i386
                  - curl
                  - winbind
                  - espeak
                  - unzip

        - name: create user gamemaster
          user:
                name: "{{ gamemaster_user }}"
                password: "{{ gamemaster_password | password_hash('sha512') }}"
                shell: /bin/bash
                update_password: on_create
          tags:
                - user
  post_tasks:
        - name: install ansible new version
          apt:
                  name: ansible
                  state: latest
          tags:
                - ansible
