---
- hosts: all localhost
  become: true
  pre_tasks:
        - name: add architecture i386
          shell: dpkg --add-architecture i386

        - name: install required packeges
          apt:
                  name: "{{ item }}"
                  state: latest
                  update_cache: true
          loop:
                  - libx11-6:i386
                  - libxext6:i386
                  - libgl1-mesa-dri:i386
                  - libgl1-mesa-glx:i386
                  - tmux
                  - mailutils
                  - postfix
                  - ca-certificates
                  - lib32gcc1
                  - libstdc++6
                  - libstdc++6:i386
                  - curl
                  - winbind
                  - espeak
                  - unzip

        - name: create user gamemaster
          user:
                name: gamemaster
                password: '$6$t01fm3ejrt$eaV74WsYdhOhOABwyVPoxOYIAQHnA/2oFDUw47wTC5qYL4u2Rmp4OW4m..1sN0vBwSYCmemRvTmd2AeBGg8Zk.'
                update_password: on_create
          tags:
                - user
