---
- hosts: all localhost
  become: true
  vars_files:
        - host_vars/electrixx-server.yml
  pre_tasks:
        - name: install ansible new version
          apt:
                  name: ansible
                  state: latest
          tags:
                - ansible

        - name: install required packages
          apt:
                  name: "{{ item }}"
                  state: latest
                  update_cache: true
          loop:
                  - python3-pip
                  - openssh-server
          tags:
                  - python

        - name: install python required
          pip:
                name: cryptography
                executable: pip3
          tags:
                - python

        - name: add architecture i386
          shell: dpkg --add-architecture i386

        - name: install required packages
          apt:
                  name: "{{ item }}"
                  state: latest
                  update_cache: true
          loop:
                  - libx11-6:i386
                  - libxext6:i386
                  - libgl1-mesa-dri:i386
                  - libgl1-mesa-glx:i386
                  - tmux
                  - mailutils
                  - postfix
                  - ca-certificates
                  - lib32gcc-10-dev
                  - libstdc++6
                  - libstdc++6:i386
                  - curl
                  - winbind
                  - espeak
                  - unzip
          tags:
                - steam

        - name: create user gamemaster
          user:
                name: "{{ gamemaster_user }}"
                password: "{{ gamemaster_password | password_hash('sha512') }}"
                shell: /bin/bash
                update_password: on_create
          tags:
                - user
                - steam

