---
- hosts: all
  become: true
  pre_tasks:
        - name: add architecture i386
          shell: dpkg --add-architecture i386

        - name: install required packeges
          apt:
                  name: "{{ item }}"
                  state: latest
                  update_cache: true
          with_items:
                  - libx11-6:i386
                  - libxext6:i386
                  - libgl1-mesa-dri:i386
                  - libgl1-mesa-glx:i386
                  - tmux
                  - mailutils
                  - postfix
                  - ca-certificates
                  - lib32gcc1
                  - libstdc++6
                  - libstdc++6:i386
                  - curl
                  - winbind
                  - espeak
                  - unzip
