---
- hosts: all
  become: true
  vars:
          - SERVER_HOME: "{{ ansible_env['HOME'] }}/server"
          - STEAM_HOME: "{{ SERVER_HOME }}/steam"
          - elektrixx_version: Iota
  pre_tasks:
        - name: create install directory
          file:
                  path: "{{ item }}"
                  state: directory
          with_items:
                  - "{{ SERVER_HOME }}"
                  - "{{ STEAM_HOME }}"
  roles:
        - role: steam
        - role: steam_csgo
