---
- hosts: all
  become: true
  vars:
          - SERVER_HOME: "{{ ansible_env['HOME'] }}/server"
          - STEAM_HOME: "{{ SERVER_HOME }}/steam"
          - elektrixx_version: Kappa
  pre_tasks:
        - name: create install directory
          file:
                  path: "{{ item }}"
                  state: directory
                  force: true
          with_items:
                  - "{{ SERVER_HOME }}"
                  - "{{ STEAM_HOME }}"

        - name: filesystem
          filesystem:
                  dev: /dev/sdb1
                  fstype: ext3

        - name: mount server disk
          mount:
                  name: "{{ SERVER_HOME }}"
                  src: /dev/sdb1
                  opts: "rw,defaults,exec"
                  fstype: auto
                  state: mounted
  roles:
       - role: steam
       - role: steam_csgo
       - role: steam_l4d2
